### ISSUE TITLE
Add design notes

### ISSUE THREAD

**Issue by soliton37** [ansys/pyaedt#5109] opened 2024-08-30 15:04 UTC
### Description of the feature

Develop a pyaedt command for adding a note to a design. 
Actually, I use this command line: hfss.odesign.editnotes(notes)
notes is a string

**Comment by Samuelopez-ansys** [comment] 2024-08-30 15:10
Hi @soliton37 , sure we can do it. But maybe you could consider doing your first contribution to PyAEDT :), everyone is welcome to contribute:

https://aedt.docs.pyansys.com/version/stable/Getting_started/Contributing.html

**Comment by gmalinve** [comment] 2024-10-10 12:47
Hi @soliton37,

This has been tackled in this PR: #5271, it's still open but soon to be closed and available in next release.
Please try to have a look at it so you can have some hints on how you could contribute to PyAEDT.

Thanks,

Regards,

Giulia

**Comment by gmalinve** [comment] 2024-10-10 12:49
Duplicate of #4613.

**Closed** 2024-10-11 13:01 UTC
Labels: enhancement
